// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "UserService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::com::test;

class UserServiceHandler : virtual public UserServiceIf {
 public:
  UserServiceHandler() {
    // Your initialization goes here
  }

  void getUserById(User& _return, const int32_t id) {
    // Your implementation goes here
    printf("getUserById\n");
  }

  void getUserByName(User& _return, const std::string& name) {
    // Your implementation goes here
    printf("getUserByName\n");
  }

  void getList(std::vector<User> & _return) {
    // Your implementation goes here
    printf("getList\n");
  }

  void addUser(const User& user) {
    // Your implementation goes here
    printf("addUser\n");
  }

  void updateUser(const User& user) {
    // Your implementation goes here
    printf("updateUser\n");
  }

  void delUser(const std::string& name) {
    // Your implementation goes here
    printf("delUser\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::apache::thrift::stdcxx::shared_ptr<UserServiceHandler> handler(new UserServiceHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new UserServiceProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

