/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "User_constants.h"

namespace com { namespace test {

const UserConstants g_User_constants;

UserConstants::UserConstants() {
}

}} // namespace

