spring:
  application:
    name: rabbitmq-hello
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#    publisher-confirms: true
#    virtual-host: /
server:
  port: 8080
  address: localhost